package main

import (
	"crypto/sha256"
	"encoding"
	"fmt"
	"log"
)

func main() {
	const (
		ex1 = "first example"
		ex2 = "second example"
	)

	firstHash := sha256.New()
	firstHash.Write([]byte(ex1))
	marshaler, ok := firstHash.(encoding.BinaryMarshaler)
	if !ok {
		log.Fatal("first hash is not generated by encoding.BinaryMarshaler")
	}
	data, err := marshaler.MarshalBinary()
	if err != nil {
		log.Fatal(err)
	}

	secondHash := sha256.New()
	unmarshaler, ok := secondHash.(encoding.BinaryUnmarshaler)
	if !ok {
		log.Fatal("not a binary unmarshaller")
	}

	if err := unmarshaler.UnmarshalBinary(data); err != nil {
		log.Fatal(err)
	}

	fmt.Printf("%x\n", data)
}
